[project]
name = "genaiwrapper"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "google-genai>=2.0.0",
    "fastapi>=0.115.0",
    "uvicorn>=0.34.0",
    "httpx>=0.28.0",
    "pydantic-settings>=2.7.0"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
genaiwrapper="genaiwrapper.main:main"

[dependency-groups]
dev = [
    { include-group = "lint" },
    { include-group = "test" }
]
lint = [
    "ruff >= 0.15.0"
]
test = [
    "pytest >= 9.0.0",
    "pytest-cov >= 7.0.0"
]

[tool.pytest]
testpaths = ["tests"]
pythonpath = ["diffuzz"]

[tool.ruff]
fix = true
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "I"]
